services:
  app_db:
    container_name: app_db
    hostname: postgres
    image: library/postgres:14.1
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts
      - ./.env:/app/.env
    ports:
      - "65432:5432"

  app_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: app_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - 36379:6379

volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"

networks:
  default:
    external: true
    name: app_main